#version 450
#if GL_KHR_vulkan_glsl
#extension GL_KHR_vulkan_glsl : enable
#endif

layout(rgba8, set = 0, binding = 0) uniform restrict writeonly image3D volume;

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;
void main()
{
	vec3 delta = gl_GlobalInvocationID.xyz - vec3(16.0);
	float l = length(delta);
	float dencity = l - 10.0f;
	imageStore(volume, ivec3(gl_GlobalInvocationID.xyz), clamp(vec4(abs(delta / l), dencity * 0.5 + 0.5), 0.0, 1.0));
}